[WIP] Attempt to change to Typescript (errors)
Attempt to change the generated app code with some components from
core/settings to support Typescript.

Still errors

   ERROR in /app/src/main.ts
   3:16-27
   [tsl] ERROR in /app/src/main.ts(3,17)
         TS2307: Cannot find module './App.vue' or its corresponding type declarations.
   ts-loader-default_e3b0c44298fc1c14