App: use Typescript by adding lang="ts"
Add @ts-expect-error to imports to fix tsc complaining about the
module not exporting type definitions

The reported error would be:

   @ts-expect-error: Cannot find module or its corresponding type declarations

Signed-off-by: Thomas Lehmann <t.lehmann@strato.de>