AuthToken*.vue: cast type for  Element with (x as T)
This works around build errors like this:

   ERROR in /app/src/components/AuthTokenSetupDialog.vue.ts
   93:29-35
   [tsl] ERROR in /app/src/components/AuthTokenSetupDialog.vue.ts(93,30)
         TS2339: Property 'select' does not exist on type 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, any>> | Element | Vue<...> | (ComponentPublicInstance<...> | ... 1 more ... | Vue<...>)[]'.
  Property 'select' does not exist on type 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, any>>'.

This is actually not a proper fix. It would be better to declare type
definitions once for the NcTextField using Typescript's

   declare module '.../NcTextField.mjs' {

   }