Change to typescript (broken)
* Add tsconfig.json (from Nextcloud)
  * "include" patterns adapted
  * "jest" removed from types for now

* Installed @vue/tsconfig because it's referenced by tsconfig.json

* Adapted filename pattern for entrypoint to .ts

* Added type declaration for "n" and "t" because in the Javascript they
  were referenced as globals (this should later be changed to some
  proper import)

Still fails with

   ERROR in /app/src/main.ts
   ./src/main.ts 2:16-27
   [tsl] ERROR in /app/src/main.ts(2,17)
         TS2307: Cannot find module './App.vue' or its corresponding type declarations.