AuthTokenSetup.vue: move data property definition *after* methods (still fails with one kind of TS error)
Merely moving the property after another fixes a Typescript error. I'm
baffled.

This fixes one of three Vue/Typescript errors:

   ERROR in /app/src/components/AuthTokenSetup.vue.ts
   47:9-14
   [tsl] ERROR in /app/src/components/AuthTokenSetup.vue.ts(47,10)
         TS2339: Property 'reset' does not exist on type 'CreateComponentPublicInstance<{}, { authTokenStore: Store<"auth-token", { tokens: IToken[]; }, {}, { updateToken(token: IToken): Promise<any>; addToken(name: string): Promise<ITokenResponse | null>; deleteToken(token: IToken): Promise<...>; wipeToken(token: IToken): Promise<...>; renameToken(token: IToken, newName: ...'.

Still fails with two other errors where Typescript can't infer types on
properties referenced via this.$refs.

Related:

* https://github.com/vuejs/vue/issues/12628#issuecomment-1283730746

Signed-off-by: Thomas Lehmann <t.lehmann@strato.de>